### ISSUE TITLE
stream not working… 

### ISSUE THREAD

**Issue by werwolf96** [callsmusic/trtmp#1]
Hi, I tried to run external links, youtube link and nothing, no message appears in the console is nothing.

![3E32645A-0191-4ADF-8204-0857AD115095](https://user-images.githubusercontent.com/82330055/163707618-0f958ed8-a6a8-47d0-9eda-2add3e6933f3.png)

![6DF7784B-39E7-4997-8DE6-23EE3ADDAB40](https://user-images.githubusercontent.com/82330055/163707653-932ea12d-b8dc-4d3a-b499-b8f43a3ab3e6.png)
![88D8F7A6-14C6-4057-B451-BDFFAE17B9F7](https://user-images.githubusercontent.com/82330055/163707654-402384b6-539a-4a15-8864-4a2182c7bfde.png)

**Comment by rojvv** [comment]
I am unable to reproduce this locally.

**Comment by rojvv** [comment]
@werwolf96 Please upgrade to the latest version, try reproducing the bug, and show me what you see.

**Comment by rojvv** [comment]
Closing in favor of https://t.me/callsmusicchat/9708.
